### ISSUE TITLE
Save functionality

### ISSUE THREAD

**Issue by NickErrant** [hDeraj/Dominodes#15]
Currently no ability to save your graphs. Should be top priority as of now, if Dominodes is to move forward as a useful tool.

**Comment by hDeraj** [comment]
Current strategy will be to save the positions of each node relative to the viewport size, and a list of edges. To load a graph, we just need to recreate all the nodes, add them to the dom, and then reconstruct the edge svgs

**Comment by hDeraj** [comment]
I'll save the sheets as json files for now (unless we can think of a reason to use something else). Sanitizing the label and formula text for security is a mild concern
