### ISSUE TITLE
Input crowding

### ISSUE THREAD

**Issue by NickErrant** [hDeraj/Dominodes#23]
Inputs are overlapping in the Input display area, possibly related to screen size (I believe the screenshot below is from a 15.6" monitor).
![crowding](https://cloud.githubusercontent.com/assets/9388050/6950160/bdafcd20-d86d-11e4-9389-18012d20b0bb.PNG)

**Comment by hDeraj** [comment]
![inputs](https://cloud.githubusercontent.com/assets/2014613/6951951/c3678824-d88c-11e4-8c2b-402058b90122.png)

Inputs now wrap correctly
